pipeline {
    agent any
    tools {
        gradle 'gradle 7.5.1' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'Build'
            }
        }
        stage('test') {
            steps {
                //sh 'gradle docker'
                echo 'test succesfull'
            }
        }
        stage('Build Docker Image') {
            steps {
                //sh 'gradle docker'
                echo 'succesfull'
            }
        }
        stage('Run Docker Image') {
            steps {
                //sh 'gradle dockerRun'
                echo 'succesfull'
            }
        }
    }
}

